name: ask_the_village
description: "A private, supportive community for real questions and real answers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  firebase_core: 4.4.0
  firebase_auth: 6.1.4
  cloud_firestore: 6.1.2
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - design/02-create-account-and-sign-in.png
